### ISSUE TITLE
Backward compatible code is missing

### ISSUE THREAD

**Issue by tempelmann** [marioaguzman/toolbar#2]
As a developer who likes to keep his code compatible with older macOS versions as much as feasible, it would be nice if your example also includes examples that work on pre-10.15 systems.

Along that, the Readme has a sub title "## macOS Catalina and older", yet the code doesn't work well on pre-Catalina systems. It should also be made clearer that the automatic conversion of a group item into a narrower one with a popup menu only works on Big Sur and later, not in Catalina.

**Comment by marioaguzman** [comment]
The collapsible segmented control does in fact work in Catalina. When I first wrote this, it was under Catalina. It's there in the screenshots.

I will remove the Catalina mentions in the README. Thanks for letting me know.

**Comment by tempelmann** [comment]
I now remember what the problem with 10.15 was: It doesn't work if you want to use icons in the segments. Works only with labels. 11.0 finally allows icons in the segments, with the labels appearing in the popup menus.
